## Site
site_name: SRE / DevOps Taiwan 讀書會
#site_author: 'Rick Hwang'
site_url: 'https://cross-community.github.io/sre/'

# Copyright
#copyright: 'Copyright &copy; 2016 - 2017 Martin Donath'


## Navigator
nav:
  - "SRE 讀書會": index.md
  - "Round 1: Site Reliability Engineering":
    - 緒論、第一章: "01_SRE/CH01.md"
    - 第二、三、四章: "01_SRE/CH02-04.md"
    - 第五、六、七章: "01_SRE/CH05-07.md"
    - 第八～十一章: "01_SRE/CH08-11.md"
    - 第十二～十五章: "01_SRE/CH12-15.md"
    - 第十六～十八章: "01_SRE/CH16-18.md"
    - 第十九～廿一章: "01_SRE/CH19-21.md"
    - 第廿二章: "01_SRE/CH22.md"
    - 第廿五章: "01_SRE/CH25.md"
    - 第廿六章: "01_SRE/CH26.md"
    - 第卅二～卅四章: "01_SRE/CH32-34.md"
  - "Round 2: Continous Delivery":
    - "第一章 軟體交付的問題": "02_CD/CH01.md"
    - "第二章 設置管理": "02_CD/CH02.md"
    - "第三章 持續整合": "02_CD/CH03.md"
    - "第四章 測試策略的實現": "02_CD/CH04.md"
    - "第五章 部署流水線": "02_CD/CH05.md"
    - "第六章 建置與佈署腳本化": "02_CD/CH06.md"
    - "第七章 提交階段": "02_CD/CH07.md"
    - "第八章 驗收測試階段": "02_CD/CH08.md"
    - "第九章 非功能需求測試": "02_CD/CH09.md"
    - "第十章 應用程式的部署與發佈": "02_CD/CH10.md"
    - "第十一章 管理基礎設施與環境": "02_CD/CH11.md"
    - "第十二章 資料管理": "02_CD/CH12.md"
    - "第十三章 元件相依性管理": "02_CD/CH13.md"
  - "SRE 經典好文": "Articles.md"
  - "事件處理案例": "Incidents.md"
  - "相關活動分享": "Events.md"


theme:
#  name: readthedocs
  name: material
  palette:
    primary: 'light blue'
    accent: 'indigo'
  logo:
    icon: 'cloud'
  language: 'zh-TW'
  feature:
    tabs: false

google_analytics: ['UA-125861317-1', 'cross-community.github.io']

extra:
  manifest: 'manifest.webmanifest'
  # https://squidfunk.github.io/mkdocs-material/getting-started/#adding-social-links
  social:
    - type: facebook
      link: https://www.facebook.com/groups/sre.taiwan/
    - type: github
      link: https://github.com/cross-community/sre/
  disqus: 'cross-community'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true